### PR TITLE
fix: duplicated test function

### PR DESCRIPTION
**Pull request by mateusoliveira43**
Fix for
```sh
$ go mod vendor && go test -v ./...
?   	github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/hack/cp-plugin	[no test files]
# github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure [github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure.test]
velero-plugin-for-microsoft-azure/object_store_test.go:171:6: TestGetBlockSize redeclared in this block
	velero-plugin-for-microsoft-azure/object_store_test.go:143:6: other declaration of TestGetBlockSize
FAIL	github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure [build failed]
FAIL

```

### CODE REVIEW

**Review by sseago — APPROVED** [review]

**Comment by mpryc** [comment]
I know it's just removing duplicated test, but the CI is complaining within unit tests on:

```
go: errors parsing go.mod:
/go/src/github.com/openshift/velero-plugin-for-microsoft-azure/go.mod:3: invalid go version '1.22.0': must match format 1.23
/go/src/github.com/openshift/velero-plugin-for-microsoft-azure/go.mod:5: unknown directive: toolchain
```


I think the second is about updating  `toolchain` version?

**Comment by mpryc** [comment]
Patch itself looks ok, it's not fixing entire CI (unit-tests) but it's removning dup functions.

/lgtm

**Review by mpryc — APPROVED** [review]

**Review by mpryc — APPROVED** [review]

**Pull request merged**
