### PR TITLE
fix: ARM images

### PR DESCRIPTION
**Pull request by mateusoliveira43**
Add ARM images to PROW CI

Related to https://github.com/openshift/release/pull/54877

### How to build
```sh
docker build -t <TAG> -f Dockerfile.ubi . --platform=linux/arm64
```

### CODE REVIEW

**Comment by mpryc** [comment]
How about multi-arch image?:
```
--platform linux/amd64,linux/arm64
```

**Comment by mateusoliveira43** [comment]
do not if that works without docker buildx

but this example is just to test ARM images, CI will create multi arch images (amd and arm) yes

**Comment by mpryc** [comment]
It should:
https://docs.docker.com/build/building/multi-platform/#building-multi-platform-images

**Comment by mateusoliveira43** [comment]
multi-arch images are slower to build than single arch. For development, I think fastest solution is better

**Review by weshayutin — APPROVED** [review]
/LGTM

**Review by kaovilai — APPROVED** [review]

**Pull request merged**
